### ISSUE TITLE
Tool not working

### ISSUE THREAD

**Issue by Achieve-Glory** [MManoah/league-profile-tool#11]
I receive an error every time I try to use this tool, I have tried opening the client first and then the tool and vice versa. I have also tried using multiple different accounts with the same result
![image](https://user-images.githubusercontent.com/59240093/90060242-64b38f00-dcb2-11ea-9b18-e279665db93e.png)

**Comment by MManoah** [comment]
Take this path from the client
![image](https://user-images.githubusercontent.com/47468428/90135864-52346680-dd41-11ea-89d4-c8f729e12f64.png)

Put the path in the clientPath text file and then save it
![image](https://user-images.githubusercontent.com/47468428/90135951-6d06db00-dd41-11ea-8feb-1343873896dc.png)

See if that fixes it

**Comment by Achieve-Glory** [comment]
looks like that fixed it

**Comment by TecentDog** [comment]
> 选择客户端的路径
> ![image](https://user-images.githubusercontent.com/47468428/90135864-52346680-dd41-11ea-89d4-c8f729e12f64.png)
> 
> 将路径放入clientPath文本文件，然后保存它
> ![image](https://user-images.githubusercontent.com/47468428/90135951-6d06db00-dd41-11ea-8feb-1343873896dc.png)
> 
> 看看这是否能解决问题

这个怎么弄，把啥子代码放进去，代码是啥
