### ISSUE TITLE
a error

### ISSUE THREAD

**Issue by ARealNOOB** [MManoah/league-profile-tool#29]
I don't know how doesn't work , I use asian server , I m chinese player
![123](https://user-images.githubusercontent.com/79206852/108214254-ebb65800-716a-11eb-8b48-ce25ba3773eb.png)

**Comment by q1820438431** [comment]
你连续点了两次，就会出现这个问题

**Comment by ARealNOOB** [comment]
问题是点一次就这样了啊。。我也不知道咋回事

**Comment by 1977964794** [comment]
所以怎么解决呢

**Comment by bpshou** [comment]
重新启动游戏是否可以解决？我也遇到了

**Comment by MManoah** [comment]
Aram boost was patched as of 11.4
