### ISSUE TITLE
Function error

### ISSUE THREAD

**Issue by weikewei110** [MManoah/league-profile-tool#30]
![image](https://user-images.githubusercontent.com/10571657/108307729-4db5a280-71e9-11eb-8322-fd7f7d92e794.png)

**Comment by bpshou** [comment]
需要在无限活力选英雄界面使用

**Comment by weikewei110** [comment]
> 需要在无限活力选英雄界面使用

谢谢，单人可以用，但是组队有问题

**Comment by MManoah** [comment]
Aram boost was patched as of 11.4
