### ISSUE TITLE
游戏界面，使用工具报错

### ISSUE THREAD

**Issue by bpshou** [MManoah/league-profile-tool#31]
![屏幕截图 2021-02-18 151105](https://user-images.githubusercontent.com/22309240/108319035-c160ab00-71fb-11eb-8eb6-a12ad586d8f4.png)

**Comment by deku772** [comment]
me too ,tx 加急

**Comment by o1f** [comment]
腾讯安排上了 - -

**Comment by 2655198887** [comment]
无了吗

**Comment by Happy-IT** [comment]
应该是腾讯封了吧，试了几局都没用。昨天还有用的

**Comment by lolly1023** [comment]
被txgank了

**Comment by 2655198887** [comment]
太快了吧

**Comment by xb0or** [comment]
午睡前还能用

**Comment by zzh1998zzh** [comment]
马服安排了

**Comment by weikewei110** [comment]
我也有这个问题，你是不是组队了？
我单人玩可以用，但是组队就报这个错误

**Comment by deku772** [comment]
单人组队都不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "weikewei110"<notifications@github.com&gt;; 
发送时间: 2021年2月18日(星期四) 晚上6:14
收件人: "MManoah/league-profile-tool"<league-profile-tool@noreply.github.com&gt;; 
抄送: "13594611244"<13594611244@163.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [MManoah/league-profile-tool] 游戏界面，使用工具报错 (#31)





 
我也有这个问题，你是不是组队了？
 我单人玩可以用，但是组队就报这个错误

**Comment by TecentDog** [comment]
我只想知道还能不能用

**Comment by deku772** [comment]
就是不能用，大伙才反馈。能不能用自己看啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TecentDog"<notifications@github.com&gt;; 
发送时间: 2021年2月18日(星期四) 晚上6:37
收件人: "MManoah/league-profile-tool"<league-profile-tool@noreply.github.com&gt;; 
抄送: "13594611244"<13594611244@163.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [MManoah/league-profile-tool] 游戏界面，使用工具报错 (#31)





 
我只想知道还能不能用

**Comment by TecentDog** [comment]
> 就是不能用，大伙才反馈.能不能用自己看啊
> […](#)
> 评论@norespony.github.com>；主题：Re：[Mmanoah/League-Profile-Tool]游戏界面，使用工具报错(#31)我只想知道还能不能用--你收到这封信是因为你评论了。直接回复这封电子邮件，在GitHub上查看，或者取消订阅。

我晓得不能用，我说二回，以后能不能用

**Comment by deku772** [comment]
？？？api都封了，还想用，乖乖充钱




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TecentDog"<notifications@github.com&gt;; 
发送时间: 2021年2月18日(星期四) 晚上6:40
收件人: "MManoah/league-profile-tool"<league-profile-tool@noreply.github.com&gt;; 
抄送: "13594611244"<13594611244@163.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [MManoah/league-profile-tool] 游戏界面，使用工具报错 (#31)





  
就是不能用，大伙才反馈.能不能用自己看啊
 …
 评论@norespony.github.com&gt;；主题：Re：[Mmanoah/League-Profile-Tool]游戏界面，使用工具报错(#31)我只想知道还能不能用--你收到这封信是因为你评论了。直接回复这封电子邮件，在GitHub上查看，或者取消订阅。
  
我晓得不能用，我说二回，以后能不能用

**Comment by Exevell** [comment]
额 垃圾马服 昨天还能用 我以为是我电脑问题还重装系统了 呜呜呜

**Comment by MManoah** [comment]
Aram boost was patched as of 11.4

**Comment by Ch-cyber-eng** [comment]
以后用不了了吗

**Comment by Ch-cyber-eng** [comment]
You can't use it anymore?
