### ISSUE TITLE
11.4 not working

### ISSUE THREAD

**Issue by zmeyski** [MManoah/league-profile-tool#32]
11.3 was working not working anymore the skin boost

**Comment by qqbbpsy** [comment]
yes.. how could we fix that anyone can help?

**Comment by Blossom-Solutions** [comment]
Seems to be an issue with the endpoint, since I dont see boost disabled in client. Request returns 500, could be the endpoint got disabled/changed. Need more info as to where did OP and that should fix it

**Comment by LEBATRUNG** [comment]
- [ ]

**Comment by qqbbpsy** [comment]
> Seems to be an issue with the endpoint, since I dont see boost disabled in client. Request returns 500, could be the endpoint got disabled/changed. Need more info as to where did OP get the endpoints, update it, and that should fix it

Yes, it seams to be a problem with the endpoint but only the owner can update/fix it. Riot will always fix it when update..

**Comment by AlanTR** [comment]
"Patched, but still work."
POST Request: "/lol-lobby-team-builder/champ-select/v1/team-boost/purchase"
See [this](https://www.unknowncheats.me/forum/league-of-legends/441684-aram-urf-skinboost-patched.html).

Don't know if it's real.

**Comment by qqbbpsy** [comment]
> "Patched, but still work."
> POST Request: "/lol-lobby-team-builder/champ-select/v1/team-boost/purchase"
> See [this](https://www.unknowncheats.me/forum/league-of-legends/441684-aram-urf-skinboost-patched.html).
> 
> Don't know if it's real.

i have saw it and i have try this method but i might do it wrong, doesn't work for me.. yes it's real hope the owner will fix it soon

**Comment by pricob** [comment]
> 
> 
> > "Patched, but still work."
> > POST Request: "/lol-lobby-team-builder/champ-select/v1/team-boost/purchase"
> > See [this](https://www.unknowncheats.me/forum/league-of-legends/441684-aram-urf-skinboost-patched.html).
> > Don't know if it's real.
> 
> i have saw it and i have try this method but i might do it wrong, doesn't work for me.. yes it's real hope the owner will fix it soon

He is not the one who actually boosted, he might promote a keylogger or something, at the end if you read the top right message, it says that the skin was unlocked and he get 100 Blue essence.
When YOU are the booster, you get 200 essence, and the rest of your team 100 each.
He might timed that boost with someone in the lobby to fake it.
Also the name is not shown in the boost message in this video, when normally it should appear

idk what to say...

**Comment by qqbbpsy** [comment]
> > > "Patched, but still work."
> > > POST Request: "/lol-lobby-team-builder/champ-select/v1/team-boost/purchase"
> > > See [this](https://www.unknowncheats.me/forum/league-of-legends/441684-aram-urf-skinboost-patched.html).
> > > Don't know if it's real.
> > 
> > 
> > i have saw it and i have try this method but i might do it wrong, doesn't work for me.. yes it's real hope the owner will fix it soon
> 
> He is not the one who actually boosted, he might promote a keylogger or something, at the end if you read the top right message, it says that the skin was unlocked and he get 100 Blue essence.
> When YOU are the booster, you get 200 essence, and the rest of your team 100 each.
> He might timed that boost with someone in the lobby to fake it.
> Also the name is not shown in the boost message in this video, when normally it should appear
> 
> idk what to say...

that you saying make no sense.. this method it work's but it is not clear how he done and request the post.
