### ISSUE TITLE
Not working after league's new update

### ISSUE THREAD

**Issue by DA-RKO** [MManoah/league-profile-tool#34]
The aram boost is not working anymore after  the new league update

**Comment by afonsobr** [comment]
F

**Comment by Kayn577G** [comment]
yeni lig ne ?

**Comment by kubakakauko** [comment]
yea it gives this error 
![image](https://user-images.githubusercontent.com/47721520/109424415-6e48de00-79db-11eb-9f9d-784dffc6b762.png)

**Comment by Rademenes16** [comment]
There are ways to bypass it

**Comment by deku772** [comment]
> There are ways to bypass it

come on guys,shall we share togather

**Comment by boristo24** [comment]
game mode aram are not working.
